[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = sqlite:///./clinical_learning.db

[loggers]
keys = root,sqlalchemy,alembic
[handlers]
keys =
[formatters]
keys =
[logger_root]
level = WARN
handlers =
[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine
[logger_alembic]
level = INFO
handlers =
qualname = alembic
